### ISSUE TITLE
More language

### ISSUE THREAD

**Issue by nguyenhoang24695** [Holastor/Blade-and-Soul-2-Localization#1]
Hi Holastor,
I'm a player of this game.
I'm from Vietnam.
I want to make a Vietnamese Version depend on your project.
Could you accept me to do this?

Thank&Brs!

nguyenhoang24695

**Comment by Holastor** [comment]
Yes, of course you can make a translation.
I created 2 folders:
1) en_to_vi_dictionary - from English.
2) kr_to_vi_dictionary - from original Korean
you can choose any, just write which one you chose, the other one I will delete
I can invite you to collaborators if you want.

**Comment by Holastor** [comment]
> Hi Holastor,
> I'm a player of this game.
> I'm from Vietnam.
> I want to make a Vietnamese Version depend on your project.
> Could you accept me to do this?
> 
> Thank&Brs!
> 
> nguyenhoang24695

Hello nguyenhoang24695,
The game does not support Vietnamese, it does not have a font.
![Screenshot 2021-08-31 182922](https://user-images.githubusercontent.com/77208679/131511410-d29c93dd-e0da-46e7-ba5b-66d1b0f8d71e.png)
it should have written vui lòng nhấn

**Comment by nguyenhoang24695** [comment]
So. Could we add new font to the game?  Example arial font?

**Comment by Holastor** [comment]
I don't think there is an option to add a font, but I'll see

**Comment by tainguyen97tp** [comment]
@nguyenhoang24695 Bạn ơi liên hệ với mình với bạn 0.3.8.9.5.0.4.6.5.6 (Zalo)
