### ISSUE TITLE
Strong support！

### ISSUE THREAD

**Issue by aolsx** [Holastor/Blade-and-Soul-2-Localization#10]
Strong support！

**Comment by Holastor** [comment]
We are working on your request.

**Comment by Holastor** [comment]
@aolsx [NEW UPDATE](https://github.com/Holastor/Blade-and-Soul-2-Localization/releases/tag/3.1.0)

**Comment by Holastor** [comment]
@aolsx [NEW UPDATE](https://github.com/Holastor/Blade-and-Soul-2-Localization/releases/tag/3.1.0)
