### ISSUE TITLE
Game Version: 0.85.2 - newpak.pak is not working on latest version of BNS 2 updated on 7 Sep. 2022 anymore.

### ISSUE THREAD

**Issue by CuongGuti** [Holastor/Blade-and-Soul-2-Localization#11]
Hello Holastor,
Thank you very much for support us to making this English Path for BNS2.

Today BNS2 just updated new version and **newpak.pak (Game Version: 0.85.2)** is not working on latest version of BNS 2 updated on 7 Sep. 2022 anymore.

Can you please help us to fix or make a new newpak.pak? Love you. Thank you so much.

Have a nice day.

**Comment by Holastor** [comment]
Fixed [Update 0.87.2](https://github.com/Holastor/Blade-and-Soul-2-Localization/releases/tag/3.2.1)
