### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by Qwekem482** [Holastor/Blade-and-Soul-2-Localization#2]
---Issue: The game crash when i try to finish the side-quest "We are a pioneering barongdan" by talking to NPC Neyan.
---Localization version: v0.3.0 English Alpha Release

---Here is sth i found in "AppData\Local\B2\Saved\Crashes", maybe it's log or sth and it was created when the game crash, maybe it can help you.
[UE4CC-Windows-609A62414C652236CDED73AE8203CEED_0000.zip](https://github.com/Holastor/Blade-and-Soul-2-Localization/files/7088710/UE4CC-Windows-609A62414C652236CDED73AE8203CEED_0000.zip)

-----My Laptop's system configuration-----
![image](https://user-images.githubusercontent.com/80797630/131623220-399bf963-ee17-428e-a78d-177b9a4df06b.png)
![image](https://user-images.githubusercontent.com/80797630/131623237-378955fa-f430-402c-a0d6-db8ba495ac43.png)
![image](https://user-images.githubusercontent.com/80797630/131623264-6b1a3c04-091e-46f8-829c-a4673e305302.png)

-----Crash image-----
![Crash noti](https://user-images.githubusercontent.com/80797630/131621699-91facdf9-fced-49dc-8570-557c606ee453.png)

-----Error Notification (Get when press PrtSc and paste)-----
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffff00

0x00007ff743105746 B2.exe!UnknownFunction []
0x00007ff74342e3e7 B2.exe!UnknownFunction []
0x00007ff743425429 B2.exe!UnknownFunction []
0x00007ff74319fc78 B2.exe!UnknownFunction []
0x00007ff7434fb4a5 B2.exe!UnknownFunction []
0x00007ff7434f92d1 B2.exe!UnknownFunction []
0x00007ff7434f9d9b B2.exe!UnknownFunction []
0x00007ff7439091d4 B2.exe!UnknownFunction []
0x00007ff7438ea11e B2.exe!UnknownFunction []
0x00007ff7432456ee B2.exe!UnknownFunction []
0x00007ff74334725b B2.exe!UnknownFunction []
0x00007ff7432388a6 B2.exe!UnknownFunction []
0x00007ff7432c2d42 B2.exe!UnknownFunction []
0x00007ff7432aa865 B2.exe!UnknownFunction []
0x00007ff7431af0a0 B2.exe!UnknownFunction []
0x00007ff743110869 B2.exe!UnknownFunction []
0x00007ff742eb6fa5 B2.exe!UnknownFunction []
0x00007ff742ebd59c B2.exe!UnknownFunction []
0x00007ff742ebd60a B2.exe!UnknownFunction []
0x00007ff742ec772f B2.exe!UnknownFunction []
0x00007ff7465103e2 B2.exe!UnknownFunction []
0x00007fffe2fc7034 KERNEL32.DLL!UnknownFunction []
0x00007fffe44a2651 ntdll.dll!UnknownFunction []

**Comment by Holastor** [comment]
I check it later. Thanks for feedback!

**Comment by Holastor** [comment]
I checked. On the first launch, I also got a crash, but the next launches of the crash were not.
