### ISSUE TITLE
Blade and Soul 2 mobile

### ISSUE THREAD

**Issue by tainguyen97tp** [Holastor/Blade-and-Soul-2-Localization#3]
Hi. I'm trying to open *.pak file for Blade and Soul 2 mobile game. I can't open *.pak file or search for Localization. Looking for help or tools to open files

**Comment by Holastor** [comment]
In the mobile version, the localization files are in the .obb file.

**Comment by tainguyen97tp** [comment]
Can you get the game font? For example(*.tff,*.otf,*.ufont) Blade and Soul 2.
Or Original File Font

**Comment by Holastor** [comment]
@tainguyen97tp [All Font Google Disk](https://drive.google.com/file/d/15V47H4g0QkOnif_qQlAyA23c3MOTNQk5/view?usp=sharing)

**Comment by tainguyen97tp** [comment]
@Holastor
I've edited. Can you try it?
https://drive.google.com/file/d/11_NTSbYeI1Sh6PWqNdK_yK0gpx26XH1r/view?usp=sharing
I use "google translate". So if there are any mistakes, please ignore them
(note: I changed some fonts. Consider using another language)

**Comment by Holastor** [comment]
@tainguyen97tp 
I don't know what should have changed?
![Screenshot 2021-09-05 092701](https://user-images.githubusercontent.com/77208679/132115288-df64b3b4-3536-4adc-a3e3-d16e1a22d49c.png)

**Comment by tainguyen97tp** [comment]
The font file is located in the file "B2_Data_00001.pak" .is that right
You use the "quick BMS" tool to decompress

**Comment by Holastor** [comment]
@tainguyen97tp 
No, they are in B2-WindowsNoEditor_00001 or B2-WindowsNoEditor_00002.
I am using UnrealPakSwitch for unpacking and packing.
