### ISSUE TITLE
Mobile Localization

### ISSUE THREAD

**Issue by Holastor** [Holastor/Blade-and-Soul-2-Localization#4]
I was able to set up localization on my phone, but I have no information where the LocalOption.json file is on other phones. 
Please, if you have root on your phone, go to root/data_mirror/data_ce/null/0/com.ncsoft.bns219/files/UE4Game/B2/Saved/Config/Option and check if this file is there and write if file there is.
If not, try to find it and write if you find it.
![Screenshot_20210905-094341308](https://user-images.githubusercontent.com/77208679/132115710-bba6f2d3-78d4-45c1-bbc8-7ccc116d7cd4.jpg)

**Comment by hoainv1807** [comment]
hi @Holastor, I found  this file in /data/data/com.ncsoft.bns219/files/UE4Game/B2/B2/Saved/Option/LocalOption.json
my phone is Rog phone 3, android 10. hope this will help you

**Comment by Holastor** [comment]
Hi @hoainv1807 Yes, thanks this will help a lot.
