### ISSUE TITLE
🐛  Cannot leave the clan with EN client

### ISSUE THREAD

**Issue by Fourris** [Holastor/Blade-and-Soul-2-Localization#5]
Title said it all as it is. So, when i tried to leave the clan i just cant. I m typing those symbols needed as confirmation but game did not see em. All I do is switched back to KR client and left. Maybe the reason is that the confirmation is also translated now as "Subscribe". Probably you just need to keep it as default: "탈퇴 신청".

P.S I also tried to type translated confirmation, it is not working aswell.

**Comment by Holastor** [comment]
@Fourris Thanks for Feedback. I found what the problem is and now I am solving it. No more screenshot needed. I found what I needed. I solved the problem.
![Screenshot 2021-09-05 195807](https://user-images.githubusercontent.com/77208679/132131407-07b2d730-dcf7-4452-bb87-64f1d8ee87f2.png)
