### ISSUE TITLE
Mobile patch not work. Release 0.4.5

### ISSUE THREAD

**Issue by hoainv1807** [Holastor/Blade-and-Soul-2-Localization#6]
mobile patch not work with release 0.4.5
old patch still work when change the name of obb to patch.18.com.ncsoft.bns219.obb, with some bug like no text in daily quest, quest distance, can not receive exp after dead.

**Comment by Holastor** [comment]
@hoainv1807  Yes I know and release hotfix https://github.com/Holastor/Blade-and-Soul-2-Localization/releases/tag/0.4.6

**Comment by hoainv1807** [comment]
Thanks for hotfix.
