### ISSUE TITLE
DESPERATE WAITING FOR NEW ENG PATCH T_T

### ISSUE THREAD

**Issue by hienle11** [Holastor/Blade-and-Soul-2-Localization#7]
- From the bottom of my heart I wish  you could publish the new English patch for the recent update.  As a poor student living under COVID-19 circumstances, I have no money to donate u, I will do it in the future. Thank you so much and I wish you and your family all the best

**Comment by Holastor** [comment]
Release [0.5.0](https://github.com/Holastor/Blade-and-Soul-2-Localization/releases/tag/0.5.0) check. and thank for your words.
